"""change user table

Revision ID: 95c68e95cc9e
Revises: e264cccf9119
Create Date: 2024-09-02 14:11:52.922091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c68e95cc9e'
down_revision = 'e264cccf9119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_unique_id'), ['unique_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_unique_id'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_column('name')
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
